### ISSUE TITLE
QA Testing

### ISSUE THREAD

**Issue by stevenlai4** [BCIT-SSD-2020-21/dotnetproject-team3_netproject#126]

**Comment by Wayl123** [comment]
I shall leave any qa finding here, for now I will ignore styling related problem as it is still being worked on.

**Comment by Wayl123** [comment]
Add promo code button currently breaks the program as it send to a path that does not have ProductIndex. 
I believe it default to the default OnPost in Cart page. 
Think about what you want to do with that button but probably make it do something that doesn't crash the program.

**Comment by Wayl123** [comment]
Right this bug technically wouldn't happen in practice but I should still mention it.
When user have multiple uncheckout cart, as soon as they checkout one cart the program will immediate grab the next cart in line when return to the home page.
I can't think of a way to solve this except to move the managecart service to the place where it only run on start of the program.

**Comment by Wayl123** [comment]
Nice spelling mistake on the alert when user try to delete an item in cart.

**Comment by Wayl123** [comment]
I don't think we will do anything with the contact us box in the footer but just in case I will mention it.
Currently it does nothing at all, doesn't clear message, doesn't validate form, just does nothing.
Which is still better than crashing the program but may just want to remove it, maybe just replace it with the telephone and email on the left.

**Comment by Wayl123** [comment]
Fun thing I found is that the login button is super wide, you can click just to the right of the BetterBuy text and still access login.

**Comment by Wayl123** [comment]
The box on the right of the cart is really long when you have lot of item in the cart.
